name: svti_attendance
description: "SVTI Attendance App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  geolocator: ^10.1.0
  http: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svti_logo.png
